# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DepDoctor < Formula
  desc ""
  homepage ""
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.2.0/dep-doctor_Darwin_arm64.tar.gz"
      sha256 "2d2857dfeb56d98057853f8e736e3ffc87c28f54c200b0ead69a9f502daefe96"

      def install
        bin.install "dep-doctor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.2.0/dep-doctor_Darwin_x86_64.tar.gz"
      sha256 "e9e60e9fe1e87f509522acf566acab7f000ec59fb67eccca0eb71b88b72a30e3"

      def install
        bin.install "dep-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.2.0/dep-doctor_Linux_arm64.tar.gz"
      sha256 "21a0e55f1fc4e0ba63a6add4728ca48927120f8a341d4ba9d1469399a655daf6"

      def install
        bin.install "dep-doctor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.2.0/dep-doctor_Linux_x86_64.tar.gz"
      sha256 "3bc45023056c4e75da875ac9c4f90a90aa59759a5aeb57b0266d8b3bf027d72f"

      def install
        bin.install "dep-doctor"
      end
    end
  end
end
