# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DepDoctor < Formula
  desc ""
  homepage ""
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.3.0/dep-doctor_Darwin_x86_64.tar.gz"
      sha256 "bc43c1c727731a4216840e0abcc80b3f7fd236887f8c083a320f70de1611c6d0"

      def install
        bin.install "dep-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.3.0/dep-doctor_Darwin_arm64.tar.gz"
      sha256 "0fe30ff7c8173891339da335b76c41d3479c8215de20f3c3970336c374dae67f"

      def install
        bin.install "dep-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.3.0/dep-doctor_Linux_x86_64.tar.gz"
      sha256 "081ee497b14d4700e4df0e4ce7daf6f6144db870ed820ca41f6e1aff92bfc419"

      def install
        bin.install "dep-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyoshidajp/dep-doctor/releases/download/v1.3.0/dep-doctor_Linux_arm64.tar.gz"
      sha256 "d95891afd27d316c34cafdf4a114587dda5d845fcbef20e7f8238448569917ae"

      def install
        bin.install "dep-doctor"
      end
    end
  end
end
